
version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: balance/nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/data/mysite.local
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5

  producer-fpm:
    build: ./docker/fpm
    working_dir: /data/mysite.local
    env_file: app/.env
    volumes:
      - ./app:/data/mysite.local
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer-fpm:
    build: ./docker/fpm
    working_dir: /data/mysite.local
    env_file: app/.env
    command: php bin/console messenger:consume async -vv
    volumes:
      - ./app:/data/mysite.local
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  # consumer:
  #   build: ./docker/consumer
  #   volumes:
  #     - ./consumer:/app
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy

networks:
  app-network: